// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sending a POST to a verification server, and checks of the owner is a member.
/// # Parameter
/// - key: ETH Wallet private-key
/// # Return
/// - True if user is a member else false.
Future<bool> checkKey({required String key}) =>
    RustLib.instance.api.crateApiHttpClientBlockchainClientCheckKey(key: key);
